import SplashScreen from './SplashScreen';
import Login from './Login';
import Register from './Register';
import ConfirmEmail from './ConfirmEmail';
import ForgotPassword from './ForgotPassword';
import NewPassword from './NewPassword';
import Home from './HomeScreen';
import Payment from './Payment';
import Inbox from './Inbox';
import Account from './Account';

export {SplashScreen};
export {Login};
export {Register};
export {ConfirmEmail};
export {ForgotPassword};
export {NewPassword};
export {Home};
export {Payment};
export {Inbox};
export {Account};
